{
 "title": "LLM dashboard",
 "time": { "from": "2024-10-02T19:58:51.732Z", "to": "2024-10-02T20:18:27.601Z" },
 "panels": [
  {
   "title": "Prompt tokens by time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT AVG(prompt_tokens), \"timestamp\" FROM conversations GROUP BY \"timestamp\" LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of queries",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(question) FROM conversations LIMIT 50 "
    },
    {
     "rawSql": "SELECT MAX(\"timestamp\") FROM feedback LIMIT 50 "
    }
   ]
  },
  {
   "title": "Conversations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT question FROM conversations LIMIT 50 "
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(response_time) FROM conversations LIMIT 50 "
    }
   ]
  },
  {
   "title": "Answers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT answer FROM conversations LIMIT 50 "
    }
   ]
  }
 ]
}